### ISSUE TITLE
chat: Вывод сообщений в Jabber-конфу. Вывод сообщений из Jabber-конфы в игру.

### ISSUE THREAD

**Issue by vegasd** [sullome/km-freeminer-mods#30]

**Comment by sullome** [comment]
Базовый функционал сделал.
Сейчас мод умеет отправлять все сообщения в конференцию. Адрес конференции и JID бота настраиваются (в моде).

Мод не умеет:
- хоть в какую-то обработку дисконнекта (от джаббера)
- в нормальную обработку приходящих сообщений

**Comment by sullome** [comment]
Приходящие сообщения теперь обрабатываются.
Команды выполняются, если записаны через #.
Чтобы бот отправлял сообщения в игру, ник в конфе должен принадлежать какому-либо нику в игре.

Библиотеки закинул (требуется LuaSocket, ещё что-то что я забыл, и verse. Verse я немного подправил). Я знаю, что это не юниксвейно и всё такое, но пока так, а после, когда у нас уже будет нормальный сервер, я думаю можно будет и подправить — это дело пары минут.

Обработка дисконнекта вроде как есть по дефолту, протестирую с десктопа.
За сим всё, мод закончен.

**Comment by sullome** [comment]
Дополнение:
Если ник в чатоконфе не принадлежит ни одному игроку на сервере, то команда выполняется от игрока `admin`.
